# Generated by Django 2.2 on 2019-05-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_daily_follow_up', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Departure time'),
        ),
    ]
