# Generated by Django 2.2 on 2019-09-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nobinobi_daily_follow_up', '0005_auto_20190923_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='child',
            field=models.ForeignKey(on_delete=models.CASCADE, to='nobinobi_child.Child'),
            preserve_default=False,
        ),
    ]
