# Generated by Django 2.2 on 2019-10-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_child', '0010_auto_20191016_1523'),
        ('nobinobi_daily_follow_up', '0007_givemedication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyTroubleshooting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nobinobi_child.Child', verbose_name='Enfant')),
                ('periods', models.ManyToManyField(to='nobinobi_child.Period', verbose_name='Périodes')),
            ],
            options={
                'verbose_name': 'Early Troubleshooting',
                'verbose_name_plural': 'Early Troubleshootings',
                'ordering': ('date',),
                'unique_together': {('child', 'date')},
            },
        ),
    ]
