# Generated by Django 2.2 on 2020-03-20 09:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_daily_follow_up', '0008_auto_20191021_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlytroubleshooting',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobinobi_child.Child', verbose_name='Child'),
        ),
    ]
