# Generated by Django 2.2 on 2020-04-01 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_daily_follow_up', '0010_add_intermediary_departure_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nobinobi_child.Child', verbose_name='Child'),
        ),
    ]
